//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDataMgtm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.Users = new HashSet<User>();
        }
    
        public int DocId { get; set; }
        public Nullable<long> AdharNo { get; set; }
        public string PanNo { get; set; }
        public string VoterId { get; set; }
        public string DrivingLicence { get; set; }
        public string AdharUrl { get; set; }
        public string PanUrl { get; set; }
        public string VoterUrl { get; set; }
        public string DrivingLicenceUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
