//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDataMgtm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string ContactNo { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Qualifications { get; set; }
        public string Class { get; set; }
        public bool IsActive { get; set; }
        public int RoleId { get; set; }
        public int AdId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public string DisplayPicture { get; set; }
        public Nullable<int> DocId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Document Document { get; set; }
        public virtual Role Role { get; set; }
        public virtual School School { get; set; }
    }
}
